### ISSUE TITLE
PageMixin

### ISSUE THREAD

**Issue by mattaebersold** [BKWLD/cloak-customer#1]
Investigate to see if I need this still
- account pages shouldn't be indexed, so there should be no seo related needs

**Comment by weotch** [comment]
I'm ok dropping this for now.  Right now it does two main things:

1. Create SEO tags
2. Support Craft Live Preview

Both aren't _really_ a thing for account pages.  I'm not really sure yet where I want the page-mixin to live in the distributed Cloak 2.0

**Comment by weotch** [comment]
FYI, I've decided that the `pageMixin` will ultimately live in `@cloak-app/craft` (which doesn't exist yet).
