### ISSUE TITLE
Check if moving the country-region-select package to the project level is OK

### ISSUE THREAD

**Issue by mattaebersold** [BKWLD/cloak-customer#12]
@weotch check out this commit, I moved the package out to a plugin in the *project-level* rather than the package level
https://github.com/BKWLD/cloak-customer/commit/783f46187160e37eee30ed7365474c6b699767da

This was because in my modal, the components weren't defined and erroring. I noticed this in their readme: 
![image](https://user-images.githubusercontent.com/435606/162045585-da8ea977-c5f0-4f87-85cb-6b4e7d6cd174.png)

So I moved it to be kicked-off earlier, rather than trying to register it in the address modal component. 

Is this the best way? This OK?

**Comment by weotch** [comment]
This is a [pretty massive package](https://bundlephobia.com/package/vue-country-region-select@2.0.16) (181kb minified).  We should find a way to load it w/o registering it globally like the author expects us to do.

**Comment by weotch** [comment]
☝️  that moves the import into the modal component.  It's working for me fine on the demo.
