### ISSUE TITLE
Clean up and globally register modal, helpers

### ISSUE THREAD

**Issue by mattaebersold** [BKWLD/cloak-customer#3]
Right now these are sprinkled in all the components that need them. Would be nice to do something like `@$formatMoney` within the component

**Comment by weotch** [comment]
Can you share a link to one of the cases you think needs cleaning up?

**Comment by mattaebersold** [comment]
Yea, for example here https://github.com/BKWLD/cloak-customer/blob/d5fcfd84aaadf399841018b58489b5199c9c7653/components/account/order-card.vue#L23

You can see that I'm importing formatMoney and mountCompontent. Feels like the things like that I'm using in multiple places could be registered by the whole package and just used like we usually do like `@$mountComponent`, etc

**Comment by weotch** [comment]
Yeah ... I've been noodling on where common helpers belong in Cloak 2.0 ... haven't come up with a specific vision for it yet ... but I'm thinking that there will be a `@cloak-app/boilerplate` package that replaces the current `@bkwld/cloak` and maybe it contains all these common helpers.  I want to make a clean way to opt-in to them so projects that don't use certain of these features don't have to load them.  And so other packages (like this one) can force the opt-in.

**Comment by mattaebersold** [comment]
ok, I understand. So I'll keep these as-is (even though I'm copying/pasting into a new helpers file for now) and then if things change I can re-visit this and refactor
