### ISSUE TITLE
Shopify theme doesn't know the path to cloak-app plugin

### ISSUE THREAD

**Issue by mattaebersold** [BKWLD/cloak-customer#5]
@weotch check this out. On the shopify theme it's trying to look in `shopify-theme/plugins` rather than go out to the package to get the initialize plugin to initially set the customer 

![image](https://user-images.githubusercontent.com/435606/161345528-a67af0ad-d187-4460-967a-23858d3b4cb5.png)

**Comment by weotch** [comment]
Can you send me a link to the repo and branch with `shopify-theme/plugins/vuex.coffee`?  I wanna make sure I'm looking in the same place.  The first thing I was gonna check was that `@cloak-app/customer` was a dependency of `shopify-theme`

**Comment by mattaebersold** [comment]
https://gitlab.com/dripdrop-hydration/dripdrop-pro/-/blob/main/shopify-theme/plugins/vuex.coffee

**Comment by weotch** [comment]
I fixed this in #15 with this:

https://github.com/BKWLD/cloak-customer/blob/ecfedf84c20ce7881a3b2bececf0ffd7e7052b25/plugins/initialize.coffee#L4

And this:

https://github.com/BKWLD/cloak-customer/blob/ecfedf84c20ce7881a3b2bececf0ffd7e7052b25/nuxt.js#L43-L45

In other words, I'm passing the path wherever this package ends up to the plugin and using Nuxt's template-compiling behavior to fix the path.  I'm doing the [same thing in @cloak-app/boilerplate](https://github.com/BKWLD/cloak-boilerplate/blob/26810159fc7de34660e64d430c4ff7d9509a3c70/plugins/inject-helper.js#L4), btw, which is where I came up with this workaround.

**Comment by weotch** [comment]
I found a better pattern than ☝️ .  Check out

https://github.com/BKWLD/cloak-customer/blob/3aab33fd7741d7e8734672d261ed5f7cd77b005f/nuxt.js#L36-L39

I'm not using the `this.addPlugin` so our plugin doesn't route through Nuxt module's template system.  Then our imports can be simple again:

https://github.com/BKWLD/cloak-customer/blob/3aab33fd7741d7e8734672d261ed5f7cd77b005f/plugins/initialize.coffee#L3-L4
