### ISSUE TITLE
Had to pass the vuex store as a prop to the modal

### ISSUE THREAD

**Issue by mattaebersold** [BKWLD/cloak-customer#6]
@weotch is this bad? `@$store` was undefined in my mounted modal. Passing it to the modal did work, **_but feels not right_**

![image](https://user-images.githubusercontent.com/435606/161451781-11bdd3ea-7d74-4ce4-ada1-17629be513db.png)

**Comment by weotch** [comment]
Hmm, I thought that the `parent: this` bit brought along all Vue plugins, like vuex.  Like [this guy said](https://stackoverflow.com/a/64173971/59160).

If that's not working, [try this idea](https://stackoverflow.com/a/44464105/59160).  Aka:

```coffee
		updateAddress: ->
			await mountComponent AddressModal,
				parent: this
				store: @$store
				propsData: address: @address
```
