### ISSUE TITLE
Encountering a strange error on deploy

### ISSUE THREAD

**Issue by mattaebersold** [BKWLD/cloak-customer#7]
@weotch check this one out: https://app.netlify.com/sites/dripdrop-pro/deploys/624b85950d596f0009d1b4b1

package mismatch? The logs seem like it's trying to use `vue@2.6.12` In cloak customer, I have `vue@2.6.11` set in package json. I tried (in vain) to target `2.6.12` thinking that might help. It's strange because it deployed fine on Fri. But I was doing a lot of dumping node_modules and re yarning... perhaps that might have something to do with it?

**Comment by mattaebersold** [comment]
I should say too that locally things are fine. Just netlify deploys are doing this

**Comment by weotch** [comment]
Ahh, I am kind of familiar with this ... there is a tight coupling between a handful of official Vue packages that are used for SSR/SSG.  I recommend either:

- Look at the history of your yarn.lock file from when you weren't having issues and copy the package blocks out of there into your yarn.lock to try and restore them to all to compatible versions
- Keep updating Vue packages until you don't get errors.   

I am surprised that you can't repro this locally.  Is your local Node version the same as Netlify is using?  Did you delete _all_ `node_modules` folders in your proj before re-yarning?  Like including those within workspace children?
