### ISSUE TITLE
Replace explicit imports with nuxt/component references

### ISSUE THREAD

**Issue by weotch** [BKWLD/cloak-customer#9]
For instance:

https://github.com/BKWLD/cloak-customer/blob/9de35417bcea7fce4bd80f53911f201e88a76c19/pages/login.vue#L14-L15

This is so we have the option of using the overriding feature of nuxt/components to replace these at the project level.

**Comment by mattaebersold** [comment]
I've gone through all the components and updated them, so now it's like: 
![image](https://user-images.githubusercontent.com/435606/162011832-d8d0b89c-e9ec-4753-b3c4-0609642e1909.png)
